PROJECT_NAME=IMP Test Framework
ENV=UAT
browser=chrome
url=https://iap.motilaloswaluat.com/ui/iap-advisory/login

#DB
db.server=10.167.203.138
db.port=24116
db.name=MOSLACEAdvisioryDB
db.username=appadmin
db.password=$ppadmin_123DB@
db.encrypt=true
db.trustServerCertificate=true
###################################

timeout=10
pageTitle=Motilal Oswal IMP
#IAP
userid=19852
password=ABC@123
clientCode=REX7049
#alwasy add new porduct in expectedProducts 
expectedProducts=NS 5Tx5T Model Portfolio,MO Signature Model Portfolio,20 Quant Momentum Model Portfolio,Prime Model Portfolio,4 Week Focus Model Portfolio
newPorduct =Prime Model Portfolio

expectedMinInvestment=\u20B91,00,000
expectedHorizon=3-5 Years
expected.current.value=\u20B9 0
product.minInvestment=\u20B91,00,000
product.horizon=3-5 Years
product.inceptionDate=01 Feb 21
product.benchmark=Nifty 200
product.methodology=Fundamental
product.noOfStocks=15-20

activation.modle.description=A concentrated portfolio that blends tactical bets with long term winners.
standard.brokerage=Standard Brokerage 1 %
cta.next.text=Next


expected.subscription.amount=\u20B90
expected.gst.amount=\u20B90
expected.required.margin=\u20B90
expected.available.amount=\u20B930,00,000

########################
api.base.url=https://iap.motilaloswaluat.com/ui/api/client/Investment/InvestmentRequest
api.key=342DB296-93C3-4A71-BDF1-A031D30C6CA5

