# ======================
# Project Configuration
# ======================
project.name=IMP Test Framework
env=uat

# ======================
# Browser Configuration
# ======================
browser=chrome

# ======================
# Application URLs
# ======================
app.base.url=https://iap.motilaloswaluat.com
app.login.path=/ui/iap-advisory/login
