# ======================
# Project Configuration
# ======================
project.name=IMP Test Framework
env=uat

# ======================
# Browser Configuration
# ======================
browser=chrome

# ======================
# Application URLs
# ======================
app.base.url=https://iap.motilaloswaluat.com/ui/iap-advisory/login
app.page.title=Motilal Oswal IMP

# ======================
# Authentication
# ======================
auth.user.id=19852
auth.user.password=ABC@123
auth.client.code=REX1257


# ======================
# Database Configuration
# ======================
db.server=10.167.203.138
db.port=24116
db.name=MOSLACEAdvisioryDB
db.username=appadmin
db.password=$ppadmin_123DB@
db.encrypt=true
db.trustServerCertificate=true
###################################

# ======================
# Product Expectations
# ======================
product.expected.list=NS 5Tx5T Model Portfolio,MO Signature Model Portfolio,20 Quant Momentum Model Portfolio,Prime Model Portfolio,Trade Sanchay Model Portfolio,Trade Vruddhi Model Portfolio,4 Week Focus Model Portfolio

product.new=Prime Model Portfolio
product.min.investment=\u20B91,00,000
product.horizon=3-5 Years
product.current.value=\u20B9 0
product.inception.date=01 Feb 21
product.benchmark=Nifty 200
product.methodology=Fundamental
product.no.of.stocks=15-20

# ======================
# Descriptions & Texts
# ======================
activation.model.description=A concentrated portfolio that blends tactical bets with long term winners.
activation.model.brokerage.standard=Standard Brokerage 1 %
activation.model.next.cta.text=Next


# ======================
# Subscription Amounts
# ======================
subscription.amount.expected=\u20B90
gst.amount.expected=\u20B90
required.margin.expected=\u20B90
available.amount.expected=\u20B930,00,000


